# Generated by Django 4.2.3 on 2023-08-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=15)),
                ('author', models.CharField(max_length=25)),
                ('content', models.TextField()),
                ('email', models.EmailField(max_length=60)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
