# Generated by Django 4.2.3 on 2023-08-15 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='blog',
            new_name='post',
        ),
    ]
