# Generated by Django 4.2.3 on 2023-08-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_orders_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='address',
            new_name='first_address',
        ),
        migrations.AddField(
            model_name='orders',
            name='second_address',
            field=models.CharField(default='No address mentioned here', max_length=400),
            preserve_default=False,
        ),
    ]
