# Generated by Django 4.2.3 on 2023-08-08 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_address_orders_first_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='first_address',
            new_name='preferred_address',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='second_address',
            new_name='second_preferred_address',
        ),
    ]
